#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "807a9d7e82c248059a25d885e70f6d6d"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "53b1a777-7469-4d25-9e72-2ed428b739dd"
preview_database_id = "53b1a777-7469-4d25-9e72-2ed428b739dd"
migrations_dir = "app/drizzle"
